import os
import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split


# ----------------------------------------
# SAMPLE DATASET (YOU WILL EXPAND THIS)
# 1 = AI text
# 0 = Human text
# ----------------------------------------
data = [
    ("This research demonstrates significant improvements in performance and scalability of systems.", 0),
    ("In conclusion, the results clearly show that the proposed method is effective.", 0),
    ("The cat sat on the mat and looked outside the window.", 0),
    ("We therefore conclude that the system exhibits optimal behavior under constraints.", 0),

    ("As an AI language model, I cannot provide personal opinions.", 1),
    ("Overall, the generated response demonstrates structured reasoning and clarity.", 1),
    ("This article was generated by a neural network trained on large datasets.", 1),
    ("Certainly! Here is a well-structured explanation of the concept.", 1),
]


texts = [t[0] for t in data]
labels = [t[1] for t in data]


# ----------------------------------------
# TRAIN / TEST SPLIT
# ----------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.25, random_state=42
)


# ----------------------------------------
# MODEL PIPELINE
# ----------------------------------------
model = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        max_features=5000
    )),
    ("clf", LogisticRegression(max_iter=1000))
])


# ----------------------------------------
# TRAIN MODEL
# ----------------------------------------
model.fit(X_train, y_train)


# ----------------------------------------
# SAVE MODEL
# ----------------------------------------
os.makedirs("app/ai", exist_ok=True)
joblib.dump(model, "app/ai/ai_model.pkl")

print("✅ AI detection model trained and saved!")